filter:
    excluded_paths: [vendor/*]

tools:
    php_cs_fixer:
        config:
            level: all
            
    php_cpd: true
    
    php_pdepend:
        excluded_dirs: [vendor]
        
    php_code_sniffer:
        config:
            standard: PSR2
            
    php_code_coverage: true

before_commands:
    - "composer install --prefer-source --dev"
